export const AUDIT_EVENTS = {
  USER_CREATED: "USER_CREATED",
  ROLE_CHANGED: "ROLE_CHANGED",
  CONSENT_ACCEPTED: "CONSENT_ACCEPTED",
  CONSENT_REVOKED: "CONSENT_REVOKED",
  ANON_SESSION_CREATED: "ANON_SESSION_CREATED",
  ASSESSMENT_CREATED: "ASSESSMENT_CREATED",
  ASSESSMENT_COMPLETED: "ASSESSMENT_COMPLETED",
  REPORT_GENERATED: "REPORT_GENERATED",
} as const;
