import { AssessmentResult } from "@/types/assessment";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import { Info, AlertTriangle, AlertCircle, CheckCircle2, Home } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CreateAccountButton } from "@/components/auth/CreateAccountButton";
import Link from "next/link";

export function AssessmentResults({ result, isAnonymous }: { result: AssessmentResult; isAnonymous?: boolean }) {
  // Determine color coding based on severity string
  const severityColors: Record<string, string> = {
    minimal: "bg-green-50 text-green-900 border-green-200 dark:bg-green-950/30 dark:border-green-900 dark:text-green-200",
    mild: "bg-blue-50 text-blue-900 border-blue-200 dark:bg-blue-950/30 dark:border-blue-900 dark:text-blue-200",
    moderate: "bg-yellow-50 text-yellow-900 border-yellow-200 dark:bg-yellow-950/30 dark:border-yellow-900 dark:text-yellow-200",
    "moderately severe": "bg-orange-50 text-orange-900 border-orange-200 dark:bg-orange-950/30 dark:border-orange-900 dark:text-orange-200",
    severe: "bg-red-50 text-red-900 border-red-200 dark:bg-red-950/30 dark:border-red-900 dark:text-red-200",
  };

  const severityKey = result.severity.toLowerCase();
  const alertColor = severityColors[severityKey] || "bg-zinc-50 text-zinc-900 border-zinc-200 dark:bg-zinc-900 dark:border-zinc-800 dark:text-zinc-100";

  let Icon = Info;
  if (severityKey === "moderate" || severityKey === "moderately severe") Icon = AlertTriangle;
  if (severityKey === "severe") Icon = AlertCircle;

  return (
    <div className="w-full max-w-6xl mx-auto flex flex-col lg:flex-row gap-8 px-4 py-8 sm:py-12 animate-in fade-in slide-in-from-bottom-4 duration-700 items-stretch">
      <Card className="flex-1 w-full relative overflow-hidden border-zinc-200 dark:border-slate-800/80 shadow-[0_8px_30px_rgb(0,0,0,0.08)] dark:shadow-2xl dark:shadow-black/50 bg-white dark:bg-slate-900 rounded-3xl p-0">
        <div className="flex flex-col bg-slate-50/80 dark:bg-slate-800/20 w-full h-full p-6 sm:p-10">
          <CardHeader className="text-center pb-2 pt-4 px-0">
            <CardTitle className="text-3xl sm:text-4xl font-heading font-bold tracking-tight text-zinc-900 dark:text-slate-50">Assessment Complete</CardTitle>
            <CardDescription className="text-base mt-3 text-zinc-500 dark:text-slate-400 max-w-md mx-auto">
              Your results have been securely generated by the LifeBack Assessment Engine.
            </CardDescription>
          </CardHeader>
          <CardContent className="pt-8 px-0 pb-0">
            <div className="flex flex-col items-center justify-center mb-10">
              <div className="text-sm font-semibold text-zinc-500 dark:text-slate-400 uppercase tracking-[0.2em] mb-3">Total Score</div>
              <div className="text-7xl sm:text-8xl font-black tracking-tighter text-zinc-900 dark:text-slate-50 drop-shadow-sm">
                {result.totalScore}
              </div>
            </div>

            {result.isHighRisk && result.riskLevel === 3 && (
              <Alert className="mb-6 bg-red-50 text-red-900 border-red-200 dark:bg-red-950/30 dark:border-red-900 dark:text-red-200 shadow-sm rounded-2xl">
                <AlertCircle className="h-5 w-5" />
                <AlertTitle className="text-lg font-semibold ml-2">Immediate Crisis Escalation</AlertTitle>
                <AlertDescription className="ml-2 mt-2 text-base leading-relaxed">
                  You indicated thoughts of self-harm nearly every day. Please know that help is available right now. 
                  <br /><br />
                  <strong>National Suicide Prevention Lifeline:</strong> Call or text 988 (US) or go to your nearest emergency room immediately.
                </AlertDescription>
              </Alert>
            )}

            {result.isHighRisk && result.riskLevel === 2 && (
              <Alert className="mb-6 bg-orange-50 text-orange-900 border-orange-200 dark:bg-orange-950/30 dark:border-orange-900 dark:text-orange-200 shadow-sm rounded-2xl">
                <AlertTriangle className="h-5 w-5" />
                <AlertTitle className="text-lg font-semibold ml-2">High Risk Alert</AlertTitle>
                <AlertDescription className="ml-2 mt-2 text-base leading-relaxed">
                  You indicated frequent thoughts of self-harm. We strongly urge you to speak with a mental health professional as soon as possible.
                  <br /><br />
                  <strong>Crisis Text Line:</strong> Text HOME to 741741 to connect with a crisis counselor 24/7.
                </AlertDescription>
              </Alert>
            )}

            {result.isHighRisk && result.riskLevel === 1 && (
              <Alert className="mb-6 bg-blue-50 text-blue-900 border-blue-200 dark:bg-blue-950/30 dark:border-blue-900 dark:text-blue-200 shadow-sm rounded-2xl">
                <Info className="h-5 w-5" />
                <AlertTitle className="text-lg font-semibold ml-2">Support Resources</AlertTitle>
                <AlertDescription className="ml-2 mt-2 text-base leading-relaxed">
                  You indicated occasional thoughts of self-harm. Support is available to help you navigate these feelings.
                  <br /><br />
                  Consider reaching out to a therapist or contacting a support hotline if you need to talk.
                </AlertDescription>
              </Alert>
            )}

            <Alert className={`mb-8 border-l-4 ${alertColor} shadow-sm rounded-2xl`}>
              <Icon className="h-5 w-5" />
              <AlertTitle className="text-lg font-semibold ml-2">Result: {result.severity}</AlertTitle>
              <AlertDescription className="ml-2 mt-2 text-base leading-relaxed opacity-90">
                {result.summary}
              </AlertDescription>
            </Alert>

            <div className="border-t border-zinc-200 dark:border-slate-800/50 pt-6 mt-6">
              <p className="text-xs sm:text-sm text-zinc-500 dark:text-slate-400 text-center px-4 leading-relaxed">
                This is a standardized assessment result. 
                Please consult with a healthcare professional for a formal diagnosis.
              </p>
            </div>
          </CardContent>
        </div>
      </Card>

      {isAnonymous && (
        <Card className="w-full lg:w-[450px] shrink-0 relative overflow-hidden border-zinc-200 dark:border-slate-800/80 shadow-[0_8px_30px_rgb(0,0,0,0.08)] dark:shadow-2xl dark:shadow-black/50 bg-white dark:bg-slate-900 rounded-3xl p-0">
          <div className="flex flex-col bg-slate-50/80 dark:bg-slate-800/20 w-full h-full p-6 sm:p-10 relative z-10">
            <CardHeader className="text-center pt-4 px-0">
              <CardTitle className="text-2xl font-heading font-bold text-zinc-900 dark:text-slate-50">Save Your Progress</CardTitle>
              <CardDescription className="text-base text-zinc-500 dark:text-slate-400 mt-2 max-w-sm mx-auto">
                Create a free account to securely store these results and unlock more features.
              </CardDescription>
            </CardHeader>
            <CardContent className="pt-4 px-0 pb-0">
              <div className="bg-white dark:bg-slate-800/50 rounded-2xl p-6 mb-8 border border-zinc-200 dark:border-slate-700/50 shadow-sm">
                <ul className="space-y-4">
                  {[
                    "Keep your assessment history securely saved",
                    "Track changes in your wellbeing over time",
                    "Access future mental health assessments",
                    "Continue right where you left off"
                  ].map((benefit, i) => (
                    <li key={i} className="flex items-start text-sm sm:text-base font-medium text-zinc-700 dark:text-slate-300">
                      <CheckCircle2 className="h-5 w-5 mr-3 text-zinc-900 dark:text-slate-50 shrink-0 mt-0.5" />
                      <span>{benefit}</span>
                    </li>
                  ))}
                </ul>
              </div>
              
              <div className="flex flex-col sm:flex-row gap-4 items-center justify-center">
                <CreateAccountButton size="lg" className="w-full sm:w-auto h-14 px-8 rounded-full font-semibold bg-zinc-900 hover:bg-zinc-800 text-white dark:bg-white dark:text-zinc-900 dark:hover:bg-zinc-200 shadow-lg shadow-black/5 dark:shadow-none transition-all hover:scale-[1.02]">
                  Create Free Account
                </CreateAccountButton>
                <Link href="/" className="w-full sm:w-auto">
                  <Button variant="outline" size="lg" className="w-full h-14 px-8 rounded-full font-medium border-2 border-zinc-200 dark:border-slate-700 text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900 dark:text-zinc-400 dark:hover:bg-slate-800 dark:hover:text-white transition-colors">
                    Maybe Later
                  </Button>
                </Link>
              </div>
            </CardContent>
          </div>
        </Card>
      )}
    </div>
  );
}
