import Link from "next/link";
import { BrainWaveSeparator } from "@/features/public/landing/components/BrainWaveSeparator";

const solutionsLinks = [
  { label: "LifeBack™ Voice", href: "/solutions/lifeback-voice" },
  { label: "LifeBack™ Video", href: "/solutions/lifeback-video" },
  { label: "LifeBack™ Genomics", href: "/solutions/life-genomics" },
  { label: "Inside SIPL", href: "/about" },
  { label: "How SIPL Works", href: "/#detection" },
  { label: "Blog", href: "/blog" },
  { label: "Career", href: "/careers" },
  { label: "Contact Us", href: "/contact" },
];

const governanceLinks = [
  { label: "FAQ", href: "/faq" },
  { label: "Dev Tools", href: "/dev-tools" },
  { label: "Terms of Use", href: "/terms" },
  { label: "Privacy Policy", href: "/privacy" },
  { label: "Security and Trust", href: "/security" },
  { label: "Ethical AI", href: "/ethical-ai" },
];

const socialLinks = [
  { label: "LinkedIn", href: "https://www.linkedin.com" },
  { label: "Twitter", href: "https://twitter.com" },
  { label: "Instagram", href: "https://www.instagram.com" },
  { label: "YouTube", href: "https://www.youtube.com" },
];

const disclaimer =
  "This report is generated by an AI-assisted behavioral screening system. It does not constitute a clinical diagnosis and is not a substitute for professional mental health evaluation. All observations are indicative only. Please review this report with a qualified mental health professional before making any decisions about your care.";

export function Footer() {
  return (
    <footer className="w-full bg-[#F5F8FC] text-[#001B65]">
      <BrainWaveSeparator />

      <div className="px-6 pb-10 pt-16 md:px-10 md:pt-20 lg:px-16 xl:px-20">
        <div className="grid gap-12 sm:grid-cols-2 lg:grid-cols-3 lg:gap-20">
          <FooterColumn title="Solutions" links={solutionsLinks} />
          <FooterColumn title="Governance" links={governanceLinks} />
          <FooterColumn title="Socials" links={socialLinks} />
        </div>

        <div className="mt-16 border-t border-[#001B65] pt-8 md:mt-20">
          <p className="max-w-6xl font-body text-base leading-7 text-[#001B65]">
            {disclaimer}
          </p>
          <p className="mt-5 font-body text-base leading-7 text-[#001B65]">
            iCall: 9152987821 | Vandrevala Foundation: 1860-2662-345 | NIMHANS: 080-46110007
          </p>
          <p className="mt-8 font-mono text-[12px] uppercase tracking-[0.14em] text-[#001B65]/70">
            © 2026 Sequoia Insilico
          </p>
        </div>
      </div>
    </footer>
  );
}

function FooterColumn({
  title,
  links,
}: {
  title: string;
  links: Array<{ label: string; href: string }>;
}) {
  return (
    <div>
      <h2 className="mb-7 font-heading text-[15px] font-bold uppercase tracking-[0.14em] text-[#001B65]">
        {title}
      </h2>
      <ul className="grid gap-4">
        {links.map((link) => {
          const isExternal = link.href.startsWith("http");

          return (
            <li key={link.label}>
              <Link
                href={link.href}
                className="font-body text-base leading-none text-[#001B65]/78 transition-colors hover:text-[#001B65] hover:underline hover:decoration-[#D4AF37] hover:underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D4AF37] focus-visible:ring-offset-4 focus-visible:ring-offset-[#F5F8FC]"
                target={isExternal ? "_blank" : undefined}
                rel={isExternal ? "noreferrer" : undefined}
              >
                {link.label}
              </Link>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
